services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Change this to your own password
      MYSQL_DATABASE: ${MYSQL_DATABASE} # Change this to your own database
      MYSQL_USER: ${MYSQL_USER} # Change this to your own user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # Change this to your own password
    volumes:
      - ./mysql_data/initdb/:/docker-entrypoint-initdb.d/
      - ./mysql_data/data/:/var/lib/mysql/
    ports:
      - ${HOST_PORT}:3306
    restart: always
    networks:
      - db_network

networks:
  db_network:
    driver: bridge